swagger: "2.0"
info:
  version: "0.0.1"
  title: CelebrateBot
paths:
  /celebrate:
    post:
      description: |
        Rises a flag in sign of celebration!
      responses:
        200:
          description: Successful response
